# Generated by Django 5.0 on 2023-12-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='secUser',
        ),
    ]
