# Generated by Django 5.0 on 2023-12-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_user_secuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='secUser',
        ),
    ]
