# Generated by Django 5.0 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_question_question_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
