# Generated by Django 5.0 on 2023-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_question_question_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
