# Generated by Django 5.0 on 2023-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contentdescription',
            field=models.TextField(default='No Context'),
        ),
    ]
