# Generated by Django 5.0 on 2023-12-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_question_contentdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='contentdescription',
            new_name='content_description',
        ),
    ]
